version: '3.7'

services:
  pulsar:
    image: apachepulsar/pulsar:2.9.1
    container_name: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
  #      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g -Dpulsar.auth.basic.conf=/pulsar/conf/.htpasswd"
      systemTopicEnabled: "true"
      topicLevelPoliciesEnabled: "true"
      transactionCoordinatorEnabled: "true"
  #      - authenticationEnabled=true
  #      - authorizationEnabled=true
  #      - authenticationProviders=org.apache.pulsar.broker.authentication.AuthenticationProviderBasic
  #      - superUserRoles=super
  #      - brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.AuthenticationBasic
  #      - brokerClientAuthenticationParameters={\"userId\":\"super\",\"password\":\"superpass\"}
    command: >
      /bin/bash -c
      " bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
